# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    name: ci
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.9, 3.10]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python Version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev

    - name: Create requirements.txt
      run: |
        pipenv run req

    - name: Lint with flake8
      run: |
        pipenv run lint

    - name: Type check with pyright
      run: |
        pipenv run typing

    - name: Test with pytest
      run: |
        pipenv run test

    - name: Build docs
      run: |
        pipenv run doc --no-open

    - name: Install package
      run: |
        pipenv install .

    - name: Run cli help
      run: |
        pipenv run start --help

    - name: Run cli test command
      run: |
        pipenv run start .
